name: Fix PHP code style issues

on: push

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
