name: Fix JavaScript Code Style

on:
  push:
    paths:
      - 'resources/js/**/*.js'
      - 'resources/js/**/*.vue'
  pull_request:
    paths:
      - 'resources/js/**/*.js'
      - 'resources/js/**/*.vue'

jobs:
  js-code-styling:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v19.7.0'

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Run Prettier
        run: npx prettier --write 'resources/js/**/*.js' 'resources/js/**/*.vue'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix JavaScript and Vue styling
          file_pattern: '*.js *.vue'
